[gwrite.my_own_plotter]
unit = "mm"
offset_x=-193
offset_y=25
scale_y=-1
document_start = "G21\n"
layer_start = "(Start Layer)\n"
line_start = "(Start Block)\n"
segment_first = """G00 Z5
G00 X{x:.4f} Y{y:.4f}
G4 P0.0
G01 Z10 F3500
"""
segment = """G01 X{x:.4f} Y{y:.4f} Z10\n"""
line_end = """G00 Z 8.0000
G4 P0.0\n"""
document_end = """G00 Z 1.0000
G4 P0.1
G00 X-208.0000 Y2.0000
M2"""
