[gwrite.clampedSketchbook]
unit = "mm"
offset_x=-203
offset_y=-10
scale_y=-1
scale_x=1
document_start = "G21\n"
layer_start = "(Start Layer)\n"
line_start = "(Start Block)\n"
segment_first = """G00 Z1
G00 X{x:.4f} Y{y:.4f}
G01 Z4 F3500
"""
segment = """G01 X{x:.4f} Y{y:.4f} Z4\n"""
line_end = """G00 Z 2.0000
G4 P0.0\n"""
document_end = """G00 Z 0.0000
G4 P0.1
G00 X-208.0000 Y2.0000
M2"""
